version: '3.6'

#To create an initial file: docker-compose run oscar-web create
#To clean all dirs: docker-compose run oscar-web clean
#shm_size needs to be set to an appropriate value and depends on the data set

services:
  oscar-web:
    build: ./src/
    image: dbahrdt/oscar-web:latest
    volumes:
    - oscar-source:/source
    - oscar-scratch-fast:/scratch/fast
    - oscar-scratch-slow:/scratch/slow
    - oscar-next:/next
    - oscar-active:/active
    - oscar-archive:/archive
    - oscar-log:/var/log/oscar-web
    #Configs are not supported in local mode
    - ${PWD}/cfg/oscar-create-user-settings.json:/etc/oscar-create/user-settings.json
    - ${PWD}/cfg/oscar-web-config.js:/etc/oscar-web/config.js
    configs:
      - source: oscar-create-cfg
        target: /etc/oscar-create/user-settings.json
        uid: '0'
        gid: '0'
        mode: 0444
      - source: oscar-web-cfg
        target: /etc/oscar-web/config.js
        uid: '0'
        gid: '0'
        mode: 0444
    environment:
      - UPDATES=enabled
      - ARCHIVE=enabled
      - CLEAN_ARCHIVE=enabled
      - OSM_SOURCE_REMOTE_URL=http://download.geofabrik.de/europe/andorra-latest.osm.pbf
      # - OSCAR_SOURCE_REMOTE_URL=file:///archive/oscar/20200306.tar.bz2
    shm_size: 4G

configs:
  oscar-create-cfg:
    file: ./cfg/oscar-create-user-settings.json
  oscar-web-cfg:
    file: ./cfg/oscar-web-config.js

volumes:
  oscar-source: {}
  oscar-scratch-fast: {}
  oscar-scratch-slow: {}
  oscar-next: {}
  oscar-active: {}
  oscar-archive: {}
  oscar-log: {}
