version: '3.6'

#To create an initial file: docker-compose run oscar-web create
#To clean all dirs: docker-compose run oscar-web clean
#shm_size needs to be set to an appropriate value and depends on the data set

services:
  oscar-web:
    build: ./src/
    image: dbahrdt/oscar-web:latest
    volumes:
    - ${OSCAR_SOURCE}:/source
    - ${OSCAR_SCRATCH_FAST}:/scratch/fast
    - ${OSCAR_SCRATCH_SLOW}:/scratch/slow
    - ${OSCAR_NEXT}:/next
    - ${OSCAR_ACTIVE}:/active
    - ${OSCAR_ARCHIVE}:/archive
    - ${OSCAR_LOG}:/var/log/oscar-web
    #Configs are not supported in local mode
    - ${PWD}/cfg/oscar-create-user-settings.json:/etc/oscar-create/user-settings.json
    - ${PWD}/cfg/oscar-web-config.js:/etc/oscar-web/config.js
    configs:
      - source: oscar-create-cfg
        target: /etc/oscar-create/user-settings.json
        uid: '0'
        gid: '0'
        mode: 0444
      - source: oscar-web-cfg
        target: /etc/oscar-web/config.js
        uid: '0'
        gid: '0'
        mode: 0444
    environment:
      - UPDATES=${OSCAR_AUTO_UPDATE}
      - ARCHIVE=${OSCAR_ARCHIVE_ACTIVE}
      - CLEAN_ARCHIVE=${OSCAR_CLEAN_ARCHIVE}
      - ROUTING=${OSCAR_ROUTING}
      - ROUTING_PRUNE_THRESHOLD=${OSCAR_ROUTING_PRUNE_THRESHOLD}
      - OSM_SOURCE_REMOTE_URL=${OSCAR_OSM_SOURCE_REMOTE_URL}
      - OSCAR_SOURCE_REMOTE_URL=${OSCAR_DATA_SOURCE_REMOTE_URL}
      - PATH_FINDER_NUM_THREADS=${PATH_FINDER_NUM_THREADS}
      - CH_CONSTRUCTOR_NUM_THREADS=${CH_CONSTRUCTOR_NUM_THREADS}
    shm_size: 4G

configs:
  oscar-create-cfg:
    file: ./cfg/oscar-create-user-settings.json
  oscar-web-cfg:
    file: ./cfg/oscar-web-config.js

volumes:
  oscar-source: {}
  oscar-scratch-fast: {}
  oscar-scratch-slow: {}
  oscar-next: {}
  oscar-active: {}
  oscar-archive: {}
  oscar-log: {}
